"""
Circuit Netlist Generator
Generates SPICE netlists for power electronics circuits
"""

from typing import Dict, Any, List
from dataclasses import dataclass

@dataclass
class ComponentValues:
    """Container for calculated component values"""
    inductance: float  # µH
    output_capacitance: float  # µF
    input_capacitance: float  # µF
    duty_cycle: float  # 0-1
    switching_frequency: float  # Hz
    input_voltage: float  # V
    output_voltage: float  # V
    load_current: float  # A

@dataclass
class SimulationParameters:
    """Simulation setup parameters"""
    simulation_time: float = 1e-3  # 1ms default
    time_step: float = 1e-6  # 1µs default
    startup_time: float = 100e-6  # 100µs startup

class BuckConverterNetlistGenerator:
    """
    Generates SPICE netlists for Buck converter circuits
    """
    
    def __init__(self):
        self.template_library = {
            'mosfet_models': {
                'IRF540N': {'vth': 4.0, 'rd': 0.044, 'ciss': 1700e-12},
                'IRFZ44N': {'vth': 4.0, 'rd': 0.025, 'ciss': 1900e-12},
                'BSC060N06NS': {'vth': 4.0, 'rd': 0.0062, 'ciss': 2500e-12}
            },
            'diode_models': {
                'MBR20100CT': {'vf': 0.5, 'trr': 35e-9},
                'STPS20L25': {'vf': 0.48, 'trr': 25e-9}
            }
        }
    
    def generate_netlist(self, 
                        component_values: ComponentValues,
                        sim_params: SimulationParameters,
                        selected_components: Dict[str, Any] = None) -> str:
        """
        Generate complete SPICE netlist for Buck converter
        
        Args:
            component_values: Calculated component values
            sim_params: Simulation parameters
            selected_components: Optional specific component selections
        
        Returns:
            Complete SPICE netlist as string
        """
        
        # Use default components if none specified
        if selected_components is None:
            selected_components = {
                'mosfet': 'IRF540N',
                'diode': 'MBR20100CT'
            }
        
        netlist_lines = [
            "* Buck Converter Circuit - Generated by Circuit Designer Pro",
            "* Automatically generated netlist",
            "",
            "* Circuit Parameters:",
            f"* Input Voltage: {component_values.input_voltage}V",
            f"* Output Voltage: {component_values.output_voltage}V", 
            f"* Load Current: {component_values.load_current}A",
            f"* Switching Frequency: {component_values.switching_frequency/1000:.1f}kHz",
            f"* Duty Cycle: {component_values.duty_cycle:.3f}",
            "",
            "* Voltage Source",
            f"Vin 1 0 {component_values.input_voltage}",
            "",
            "* Input Capacitor",
            f"Cin 1 0 {component_values.input_capacitance}u IC=0",
            "",
            "* Main Switch (MOSFET)",
            "M1 2 3 0 0 MOSFET_MODEL",
            "",
            "* Freewheeling Diode", 
            "D1 0 2 DIODE_MODEL",
            "",
            "* Inductor",
            f"L1 2 4 {component_values.inductance}u IC=0",
            "",
            "* Output Capacitor",
            f"Cout 4 0 {component_values.output_capacitance}u IC={component_values.output_voltage}",
            "",
            "* Load Resistor",
            f"Rload 4 0 {component_values.output_voltage / component_values.load_current:.3f}",
            "",
            "* PWM Control Signal",
            self._generate_pwm_source(component_values),
            "",
            "* Component Models",
            self._generate_component_models(selected_components),
            "",
            "* Simulation Commands",
            self._generate_simulation_commands(sim_params),
            "",
            ".end"
        ]
        
        return "\n".join(netlist_lines)
    
    def _generate_pwm_source(self, component_values: ComponentValues) -> str:
        """Generate PWM voltage source for gate drive"""
        period = 1.0 / component_values.switching_frequency
        on_time = period * component_values.duty_cycle
        off_time = period * (1 - component_values.duty_cycle)
        
        return f"""* PWM Gate Drive (12V high, 0V low)
Vpwm 3 0 PULSE(0 12 0 10n 10n {on_time} {period})"""
    
    def _generate_component_models(self, selected_components: Dict[str, Any]) -> str:
        """Generate SPICE models for selected components"""
        
        mosfet_model = selected_components.get('mosfet', 'IRF540N')
        diode_model = selected_components.get('diode', 'MBR20100CT')
        
        mosfet_params = self.template_library['mosfet_models'].get(mosfet_model, 
                                                                 self.template_library['mosfet_models']['IRF540N'])
        diode_params = self.template_library['diode_models'].get(diode_model,
                                                               self.template_library['diode_models']['MBR20100CT'])
        
        models = [
            f"* MOSFET Model ({mosfet_model})",
            f".model MOSFET_MODEL NMOS(VTO={mosfet_params['vth']} RD={mosfet_params['rd']} CISS={mosfet_params['ciss']})",
            "",
            f"* Diode Model ({diode_model})", 
            f".model DIODE_MODEL D(IS=1e-14 RS=0.01 VJ={diode_params['vf']} TT={diode_params['trr']})"
        ]
        
        return "\n".join(models)
    
    def _generate_simulation_commands(self, sim_params: SimulationParameters) -> str:
        """Generate simulation control commands"""
        
        commands = [
            "* Simulation Setup",
            f".tran {sim_params.time_step} {sim_params.simulation_time} {sim_params.startup_time}",
            "",
            "* Initial Conditions",
            ".ic V(4)=0",  # Output starts at 0V
            "",
            "* Analysis Options",
            ".options gmin=1e-12 abstol=1e-12 reltol=1e-6",
            ".options plotwinsize=0"
        ]
        
        return "\n".join(commands)
    
    def generate_analysis_commands(self, analysis_type: str = "transient") -> List[str]:
        """
        Generate specific analysis commands for different simulation types
        """
        
        if analysis_type == "transient":
            return [
                "* Transient Analysis - Startup and Steady State",
                ".tran 1u 2m 0 1u",
                ".probe V(4) I(L1) V(2)"
            ]
        
        elif analysis_type == "ac":
            return [
                "* AC Analysis - Frequency Response", 
                ".ac dec 100 1 1meg",
                ".probe vdb(4) vp(4)"
            ]
        
        elif analysis_type == "load_step":
            return [
                "* Load Step Response",
                ".tran 100n 500u 0 100n",
                "* Load step at 200us",
                "Rload2 4 0 PULSE(100 50 200u 1n 1n 100u 1m)",  # Load step
                ".probe V(4) I(L1)"
            ]
        
        return []

def create_buck_simulation(input_voltage: float,
                         output_voltage: float, 
                         load_current: float,
                         switching_frequency: float,
                         calculated_components: Dict[str, float],
                         selected_parts: Dict[str, Any] = None) -> str:
    """
    Convenience function to create Buck converter simulation netlist
    
    Args:
        input_voltage: Input voltage in V
        output_voltage: Output voltage in V
        load_current: Load current in A
        switching_frequency: Switching frequency in Hz
        calculated_components: Dictionary with L, Cout, Cin values
        selected_parts: Optional specific component selections
    
    Returns:
        Complete SPICE netlist string
    """
    
    # Create component values object
    component_values = ComponentValues(
        inductance=calculated_components.get('inductance', 10.0),  # µH
        output_capacitance=calculated_components.get('output_capacitance', 10.0),  # µF
        input_capacitance=calculated_components.get('input_capacitance', 100.0),  # µF
        duty_cycle=output_voltage / input_voltage,
        switching_frequency=switching_frequency,
        input_voltage=input_voltage,
        output_voltage=output_voltage,
        load_current=load_current
    )
    
    # Create simulation parameters
    sim_params = SimulationParameters(
        simulation_time=2e-3,  # 2ms simulation
        time_step=1e-6,        # 1µs steps
        startup_time=100e-6    # 100µs startup time
    )
    
    # Generate netlist
    generator = BuckConverterNetlistGenerator()
    return generator.generate_netlist(component_values, sim_params, selected_parts)